my_dbt_project:
  outputs:
    dev:
      dataset: analytics
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /root/.config/gcloud/dbt-service-key.json
      location: US
      method: service-account
      priority: interactive
      project: dbt-poc-469617
      threads: 1
      type: bigquery
  target: dev
