version: 2

models:
  - name: stg_sales
    description: "Staging model for sales raw data"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
  - name: int_sales_summary
    description: "Aggregated sales summary per customer"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
